version: 1.0.0.{build}
image: Visual Studio 2017

# prevent the double build when a branch has an active PR
skip_branch_with_pr: true

install:
  - choco install gitversion.portable -pre -y

before_build:
  - git submodule -q update --init
  - cmd: dotnet --version
  - ps: c:\ProgramData\chocolatey\lib\gitversion.portable\tools\gitversion.exe /l console /output buildserver

build_script:
- cmd: build.cmd

test_script:
- tests\CodeCoverage\CodeCoverage.cmd

after_test:
  - cmd: appveyor PushArtifact "artifacts\SixLabors.ImageSharp.%GitVersion_NuGetVersion%.nupkg"
  - cmd: appveyor PushArtifact "artifacts\SixLabors.ImageSharp.Drawing.%GitVersion_NuGetVersion%.nupkg"

deploy:
    # MyGet Deployment for builds & releases
  - provider: NuGet
    server: https://www.myget.org/F/sixlabors/api/v2/package
    symbol_server: https://www.myget.org/F/sixlabors/symbols/api/v2/package
    api_key:
      secure: V/lEHP0UeMWIpWd0fiNlY2IgbCnJKQlGdRksECdJbOBdaE20Fl0RNL7WyqHe02o4
    artifact: /.*\.nupkg/
    on:
      branch: master
